runtime: java11
entrypoint: java -Xmx64m -jar leap-sls-service/target/leap-sls-service.0.0.1.jar
env_variables:
  LEAP_DB_URL: jdbc:mysql://google/$DB_NAME?cloudSqlInstance=$CLOUD_SQL_CONNECTION_NAME&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
  LEAP_DB_USER: $DB_USER
  LEAP_DB_PASS: $DB_PASS
