steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['package']
  - name: 'gcr.io/cloud-builders/gcloud'
    env: ['DB_NAME=${_DB_NAME}', 'CLOUD_SQL_CONNECTION_NAME=${_CLOUD_SQL_CONNECTION_NAME}','DB_USER=${_DB_USER}', 'DB_PASS=${_DB_PASS}']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i "s/__DB_NAME/${_DB_NAME}/g" app.yaml && sed -i "s/__CLOUD_SQL_CONNECTION_NAME/${_CLOUD_SQL_CONNECTION_NAME}/g" app.yaml && sed -i "s/__DB_USER/${__DB_USER}/g" app.yaml && sed -i "s/__DB_PASS/${__DB_PASS}/g" app.yaml && gcloud app deploy app.yaml
