server:
  port: ${PORT:9091}
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${LEAP_DB_URL:"jdbc:mysql://localhost:3306/leap?createDatabaseIfNotExist=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false"}
    username: ${LEAP_DB_USER:root}
    password: ${LEAP_DB_PASS:changeme}
  jpa:
    hibernate.ddl-auto: create
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl    
    properties.hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: false
    show-sql: false
    
fhir:
  r4:
    baseurl: ${HAPI_FHIR_URL:"http://localhost:8080/hapi-fhir-jpaserver/fhir/"}
