version: '3.6'

services:
  leap-mysql:
    image: mysql:latest
    container_name: leap-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'leap'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - 3308:3306
    volumes:
      - leap-mysql:/var/lib/mysql
  leap-sls-service:
    image: leap-sls-service
    container_name: leap-sls-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LEAP_DB_PASS: ${LEAP_DB_PASS}
      LEAP_DB_USER: ${LEAP_DB_USER}
      LEAP_DB_URL: ${LEAP_DB_URL}
    ports:
      - 9091:9091
volumes:
  leap-mysql: